# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_ticket_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='authodr',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
